version: 2.1

orbs:
  maven: circleci/maven@0.0.12

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
  build_artifact:
    jobs:
      - build

jobs:
  build:
    machine:
     image: ubuntu-2004:202010-01
    steps:
      - checkout
      - restore_cache:
            key: v1-calculator-{{ checksum "pom.xml" }}
      - run: mvn package -DskipTests
      - store_artifacts:
          path: target/calculator*.jar
          destination: calculator.jar
      - save_cache:
          key: v1-calculator-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2
